### PR TITLE
Add ETA to PRODQ Screen

### PR DESCRIPTION
**Pull request by deveth0**
I added the ETA to the ProdQ screen (requested in PrUn Galactic Senate). To simplify the debugging, I also enabled the plugin for localhost, hope that does not cause any problems.

### CODE REVIEW

**Comment by YarekTyshchenko** [comment]
Hmm, I think adding localhost to the manifest isn't good. I feel like they might reject it again. Also I need to make the description match what we have on the store, I think it gets overwritten by manifest every time. I'll have a look at this in a few hours and get back to you

**Comment by deveth0** [comment]
Sure, we can also just revert that part:)

**Comment by YarekTyshchenko** [comment]
~~Yea Ok, replace the description field with~~

And bump the version number, and we are good.

Edit: Actually, forget about the decsription field, lets check if they actually use it for the webstore text. I have a feeling its set manually via the UI.

**Comment by deveth0** [comment]
done :)

**Pull request merged**
